# Generated by Django 4.0.4 on 2022-05-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
